### ISSUE TITLE
Unable to see clock when using a Theme other than Default

### ISSUE THREAD

**Issue by muckypaws** [ManuelMcLure/OctoPrint-NavbarClock#2]
When using NavClock it works well with the Default theme, however if I change the Theme to another colour, the clock doesn't choose a contrasting colour to enable it to be seen.

I am using the latest V1.4

Kind Regards
Jason

![Screenshot 2021-06-10 at 14 39 52](https://user-images.githubusercontent.com/7505779/121535129-c7240b80-c9f9-11eb-8178-f2b776221bbe.png)

![Screenshot 2021-06-10 at 14 39 37](https://user-images.githubusercontent.com/7505779/121535119-c4c1b180-c9f9-11eb-8615-d9ac32d72243.png)

**Comment by ManuelMcLure** [comment]
What theming engine are you using (UICustomizer, Themeify) and which theme? Also, what other plugins do you have installed that affect the navbar? It looks like you might have Navbar Temp installed.

**Comment by ManuelMcLure** [comment]
Part of the reason I ask is that with the theme I'm using (Discorded from UICustomizer) the Navbar Temp data appears in the same color/shade as the Navbar Clock, while with your theme the color is different, so I need to figure out what Navbar Temp is doing differently.

**Comment by muckypaws** [comment]
Hey Manuel,

I am using the in-built Appearance Config that comes as default with the OctoPrint installation.

I.e. Configuration -> Appearance -> Then select any of the colours in the drop down box.

I hope this helps.

Kind Regards
Jason

**Comment by ManuelMcLure** [comment]
Please test the new 1.0.5 release - it should fix both of your issues.
