### ISSUE TITLE
Formatting and location of Time - Unclear

### ISSUE THREAD

**Issue by muckypaws** [ManuelMcLure/OctoPrint-NavbarClock#3]
V1.3 Seemed to have addressed the issue, but V1.4 installed today, seems to blend in with another plug in and doesn't have a space separator between plug-ins and time.

Kind Regards
Jason

![Screenshot 2021-06-10 at 14 39 37](https://user-images.githubusercontent.com/7505779/121535554-2d109300-c9fa-11eb-89b8-8eb99a817139.png)

**Comment by ManuelMcLure** [comment]
Please test the new 1.0.5 release - it should fix both of your issues.

**Comment by muckypaws** [comment]
Hey Manuel,

I can confirm that both issues have been resolved.

Thank you so much for providing a very speedy solution :) 

Kind Regards
Jason
