### ISSUE TITLE
theme broken (v1.0.5)

### ISSUE THREAD

**Issue by roboraptor** [ManuelMcLure/OctoPrint-NavbarClock#4]
After update to 1.0.5 it just broke whole page. 
Changed theme to white and icon from wifi state is sized to fit whole page :D . 
Ooof...

**Comment by roboraptor** [comment]
Before it looked like this (i disabled the plugin for the picture) 
![obrazek](https://user-images.githubusercontent.com/17791899/121672545-378d6400-cab0-11eb-9dd0-baa8b8078111.png)

Now it looks like this :D 
![obrazek](https://user-images.githubusercontent.com/17791899/121672871-98b53780-cab0-11eb-9d7e-ea1183cd5576.png)

I found the plugin really useful as I have the page on tablet in kiosk mode and this is really bad  :D

**Comment by roboraptor** [comment]
Also im using Themify.

Downgraded to 1.0.4 https://github.com/ManuelMcLure/OctoPrint-NavbarClock/archive/1.0.4.zip
![obrazek](https://user-images.githubusercontent.com/17791899/121674354-3d844480-cab2-11eb-976f-29a6b6823b72.png)


I guess solution is branching for Themify, UIcustomizer and Default appearance styles... 
Because fixing it for one will break it for the other...

**Comment by Taomyn** [comment]
Confirm the same issue

**Comment by ManuelMcLure** [comment]
Are you using both Themeify and UICustomizer at the same time? I can't reproduce this and I tested with all themes in Themeify as well as testing all themes in UICustomizer, but I did not test both at once.

**Comment by ManuelMcLure** [comment]
Also, what browser is this?

**Comment by ManuelMcLure** [comment]
Also, make sure you reload the page entirely with Ctrl+Shift+R - I have seen strange things happen with themes on a simple reload.

**Comment by ManuelMcLure** [comment]
Even though I can't reproduce this, I found something that might be a problem. Please test the new 1.0.6 release.

**Comment by ManuelMcLure** [comment]
I managed to reproduce this and can confirm that for me the new 1.0.6 release fixes it.

**Comment by Taomyn** [comment]
> I managed to reproduce this and can confirm that for me the new 1.0.6 release fixes it.

Confirm as well - was delayed trying it as I had managed to hit the update check limit and could not download it
